options:
  prev_tag: versio-prev

projects:
- name: whatismyip
  id: 1
  tag_prefix: ''
  labels: cargo
  version:
    file: Cargo.toml
    toml: package.version
  also:
  - file: docs/cli-usage.md
    pattern: fast-conventional (\d+\.\d+\.\d+)
  hooks:
    post_write: cargo fetch

sizes:
  use_angular: true
  none: [ci, '-']
