name: Test
on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_UPGRADE: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  test:
    runs-on: docker
    name: "Tests"
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: PurpleBooth/common-pipelines/actions/install-specdown@main
        name: Install specdown
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
      - uses: PurpleBooth/common-pipelines/actions/install-just@main
        name: Install just
      - run: just lint
      - run: just test
      - run: |
          sudo apt-get update
          sudo apt-get install -y socat
        name: apt-get install -y socat
      - run: just specdown

  release:
    if: github.ref == 'refs/heads/main'
    needs:
    - test

    runs-on: docker
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
      - uses: PurpleBooth/common-pipelines/actions/install-cocogitto@main
        name: Install Cocogitto
      - run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
        name: apt-get install -y libssl-dev
      - uses: PurpleBooth/common-pipelines/actions/configure-git-user@main
        name: Configure git user
      - run: cog bump --auto
