name: Test
on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_UPGRADE: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  test:
    runs-on: docker
    name: "Tests"
    steps:
      - uses: actions/checkout@v3.5.3
        name: Checkout
      - uses: specdown/setup-specdown-action@0.2.9
        name: Install specdown
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install cargo
      - uses: extractions/setup-just@v1
        name: Install just
      - run: rustup toolchain install nightly --component rustfmt --component clippy --allow-downgrade
        name: rustup toolchain install nightly
      - run: just lint
      - run: just test
      - run: |
          sudo apt-get update
          sudo apt-get install -y socat
        name: apt-get install -y socat
      - run: just specdown

  release:
    if: github.ref == 'refs/heads/main'
    needs:
    - test
    outputs:
      version_bump: ${{ steps.release.outputs.version_bump }}
      current_version: ${{ steps.release.outputs.current_version }}
      previous_version: ${{ steps.release.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: PurpleBooth/versio-release-action@965e279326016054156ba8bec4f733e0ee327956 # v0.1.18
      id: release


  release-binary:
    if: needs.release.outputs.version_bump
    needs:
    - release
    uses: PurpleBooth/common-pipelines/.github/workflows/release-rust-binary.yml@main
    with:
      current_version: ${{ needs.release.outputs.current_version }}
      previous_version: ${{ needs.release.outputs.previous_version }}
    secrets:
      cargo_token: ${{ secrets.CARGO_TOKEN }}
      committer_token: ${{ secrets.COMMITTER_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
