name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_UPGRADE: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        name: Checkout
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: command -v specdown >/dev/null 2>&1 || cargo install specdown --git https://github.com/specdown/specdown.git
        name: Install specdown
      - uses: PurpleBooth/common-pipelines/actions/install-just@main
        name: Install just
      - run: just lint

  unit-test:
    runs-on: docker
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        name: Checkout
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: PurpleBooth/common-pipelines/actions/install-just@main
      - run: just test

  integration-test:
    runs-on: docker
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        name: Checkout
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: command -v specdown >/dev/null 2>&1 || cargo install specdown --git https://github.com/specdown/specdown.git
        name: Install specdown
      - uses: PurpleBooth/common-pipelines/actions/install-just@main
      - run: |
          apt-get update
          apt-get install -y socat
        name: apt-get install -y socat
      - run: just specdown

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - unit-test
      - integration-test
      - lint
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: docker
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.FJ_TOKEN }}
          fetch-depth: 0
      - uses: PurpleBooth/common-pipelines/actions/install-rust@main
        name: Install rust
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Get tags
        run: git fetch --tags origin
      - shell: bash
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: GITHUB_TOKEN="$GH_TOKEN" cargo binstall --no-confirm cargo-edit
      - shell: bash
        run: GITHUB_TOKEN="$GH_TOKEN" cargo binstall --no-confirm --locked cocogitto
      - id: previous_version
        run: |
          cog get-version | tee .version
          echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash
      - name: Semver release
        id: release
        run: |
          git config --global user.name "cog-bot"
          git config --global user.email "cog@example.com"
          cog bump --auto --skip-ci
      - id: current_version
        run: |
          cog get-version | tee .version
          echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
          rm .version
        shell: bash

  bake-edge-build:
    if: needs.release.outputs.current_version == needs.release.outputs.previous_version
    runs-on: docker
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.FJ_TOKEN }}
      - run: echo "repository=$( echo "codeberg.org/$REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        id: docker
        name: Turn repository name into docker registry name
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta-without-version
        uses: docker/metadata-action@v5
        with:
          bake-target: docker
          images: ${{ steps.docker.outputs.repository }}
          tags: |
            type=edge,branch=main
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Bake Docker (without version)
        uses: docker/bake-action@v4
        with:
          set: |
            cache-from: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache
            cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache,mode=max
            docker.args.VER=${{ needs.release.outputs.current_version }}
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-without-version.outputs.bake-file-tags }}
            ${{ steps.meta-without-version.outputs.bake-file-annotations }}
            ${{ steps.meta-without-version.outputs.bake-file-labels }}
          targets: docker
      - name: Bake Bins (without version)
        uses: docker/bake-action@v4
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}
          GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        with:
          set: |
            cache-from: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache
            cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache,mode=max
            bins*.args.VER=${{ needs.release.outputs.current_version }}
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-without-version.outputs.bake-file-tags }}
            ${{ steps.meta-without-version.outputs.bake-file-annotations }}
            ${{ steps.meta-without-version.outputs.bake-file-labels }}
          targets: bins
      - shell: bash
        name: "Flatten filenames"
        run: |
          for I in target/bins/*/*/* ; do
            mv -v "$I" "target/bins/$(echo "$I" | cut -d '/' -f 3- | tr "/" "-")"
          done
          find target/bins/ -type d -empty -delete
      - uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        name: Upload binaries
        with:
          name: built-bins
          path: target/bins/

  bake-release-build:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
      - release
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FJ_TOKEN }}
          lfs: true
          ref: v${{ needs.release.outputs.current_version }}
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ github.actor }}
          password: ${{ secrets.FJ_TOKEN }}
      - run: echo "repository=$( echo "codeberg.org/$REPOSITORY" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        id: docker
        name: Turn repository name into docker registry name
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Extract versioned metadata (tags, labels) for Docker
        id: meta-with-version
        uses: docker/metadata-action@v5
        with:
          bake-target: docker
          images: ${{ steps.docker.outputs.repository }}
          tags: |
            type=edge,branch=main
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest
            type=semver,pattern={{version}},value=v${{ needs.release.outputs.current_version }},prefix=v
            type=semver,pattern={{version}},value=v${{ needs.release.outputs.current_version }}
            type=sha
      - name: Bake Docker (with version)
        uses: docker/bake-action@v4
        with:
          set: |
            cache-from: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache
            cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache,mode=max
            docker.args.VER=${{ needs.release.outputs.current_version }}
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-with-version.outputs.bake-file-tags }}
            ${{ steps.meta-with-version.outputs.bake-file-annotations }}
            ${{ steps.meta-with-version.outputs.bake-file-labels }}
          targets: docker
      - name: Bake Bins (with version)
        uses: docker/bake-action@v4
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}
          GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
        with:
          set: |
            bins*.args.VER=${{ needs.release.outputs.current_version }}
            cache-from: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache
            cache-to: type=registry,ref=${{ steps.docker.outputs.repository }}:buildcache,mode=max
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-with-version.outputs.bake-file-tags }}
            ${{ steps.meta-with-version.outputs.bake-file-annotations }}
            ${{ steps.meta-with-version.outputs.bake-file-labels }}
          targets: bins
      - shell: bash
        name: "Flatten filenames"
        run: |
          for I in target/bins/*/*/* ; do
            mv -v "$I" "target/bins/$(echo "$I" | cut -d '/' -f 3- | tr "/" "-")"
          done
          find target/bins/ -type d -empty -delete
      - uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        name: Upload binaries
        with:
          name: built-bins
          path: target/bins/


  github-release:
    needs:
      - bake-release-build
      - release
    runs-on: ubuntu-latest
    env:
      VER: ${{ needs.release.outputs.current_version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout the repository
        with:
          ref: v${{ needs.release.outputs.current_version }}
          fetch-depth: 0
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        name: Setup Cache
        with:
          path: |
            .cache
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          path: bins
          pattern: built-bins
        name: Retrieve assets
      - uses: cargo-bins/cargo-binstall@main
        name: Install cargo binstall
      - shell: bash
        run: cargo binstall --no-confirm --locked cocogitto
      - run: cog changelog --at "$TAG_V" > CHANGELOG.md
        shell: bash
        env:
          TAG_V: v${{ needs.release.outputs.current_version }}
      - name: Add hashes to release
        run: |
          {
            echo ""
            echo ""
            echo "## Hashes"
            echo ""
            (
              cd ./bins/built-bins
              for file in *; do
                if [[ -f "$file" ]]; then
                  echo " * $( sha256sum "$file" )"
                fi
              done
            )
          } >> CHANGELOG.md
      - id: release_notes
        run: |
          echo 'release_notes<<EOF' >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - uses: actions/forgejo-release@v2
        with:
          direction: upload
          title: Release v${{ needs.release.outputs.current_version }}
          tag: v${{ needs.release.outputs.current_version }}
          url: https://code.forgejo.org
          release-dir: ./bins/built-bins
          release-notes: ${{ steps.release_notes.outputs.release_notes }}
